if(EXISTS "${HEADER}")
    if(EXISTS "${PATH}")
        if("${HEADER}" IS_NEWER_THAN "${PATH}")
            return()
        endif()
    endif()
endif()

message("Current source directory: ${CMAKE_CURRENT_SOURCE_DIR}")

if(EXISTS "${PATH}")
    file(READ "${PATH}" hex_content HEX)

    string(REPEAT "[0-9a-f]" 32 pattern)
    string(REGEX REPLACE "(${pattern})" "\\1\n        " content "${hex_content}")

    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1, " content "${content}")

    string(REGEX REPLACE ", $" "" content "${content}")

    string(REPLACE "/" "::" SUB_NAMESPACE "${SUB_DIRECTORY}")

    set(array_definition "namespace Isonia::Shaders${SUB_NAMESPACE}\n{\n    /// <summary>\n    /// Autogenerated SPIR-V code representing the compiled shader.\n    /// </summary>\n    static const unsigned char ${GLOBAL}[] = {\n        ${content}\n    };\n}")
    
    get_filename_component(file_name ${HEADER} NAME)
    set(source "/**\n * @file ${file_name}\n * @brief Auto generated file.\n */\n#pragma once\n${array_definition}\n")

    file(WRITE "${HEADER}" "${source}")
else()
    message("ERROR: ${PATH} doesn't exist")
    return()
endif()
