if(EXISTS "${SHADER_HEADER}")
    if(EXISTS "${SHADER_SPV}")
        if("${SHADER_HEADER}" IS_NEWER_THAN "${SHADER_SPV}")
            return()
        endif()
    endif()
endif()

if(EXISTS "${SHADER_SPV}")
    file(READ "${SHADER_SPV}" hex_content HEX)

    string(REPEAT "[0-9a-f]" 32 pattern)
    string(REGEX REPLACE "(${pattern})" "\\1\n        " content "${hex_content}")

    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1, " content "${content}")

    string(REGEX REPLACE ", $" "" content "${content}")

    string(REPLACE "/" "::" SUB_NAMESPACE "${SHADER_SUB_DIRECTORY}")

    set(array_definition "namespace Isonia::Shaders${SUB_NAMESPACE}\n{\n    /// <summary>\n    /// Autogenerated SPIR-V code representing the compiled shader.\n    /// </summary>\n    static const constexpr unsigned char ${GLOBAL_SHADER_VAR}[] = {\n        ${content}\n    };\n}")
    
    get_filename_component(file_name ${SHADER_HEADER} NAME)
    set(source "/**\n * @file ${file_name}\n * @brief Auto generated file.\n */\n#pragma once\n${array_definition}\n")

    file(WRITE "${SHADER_HEADER}" "${source}")
else()
    message("ERROR: ${SHADER_SPV} doesn't exist")
    return()
endif()
